version: '2'

services:

    sass-watcher:
        image: sass-watcher
        build: ./sass-watcher
        volumes:
            - "./html/css:/app/css"
            - "./templates/styles.scss:/app/sass/styles.scss:ro"

    html-watcher:
        image: watch-make
        build: ./html-watcher
        volumes:
            - "./html:/app/html"
            - "./Makefile:/app/Makefile:ro"
            - "./templates:/app/templates:ro"

    http-server:
        image: python:2-alpine
        ports:
            - "127.0.0.1:8000:8000"
        volumes:
            - "./html:/app"
        working_dir: /app
        command: python -m SimpleHTTPServer

