version: '2'

services:

    node:
        image: node:lts-alpine
        restart: always
        volumes:
            - "./html:/app"
        working_dir: /app
        command: npm start

    python:
        image: python:2-alpine
        restart: always
        ports:
            - "127.0.0.1:8000:8000"
        volumes:
            - "./html:/app"
        working_dir: /app
        command: python -m SimpleHTTPServer

