<!DOCTYPE html>
<html lang="de">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Keine Gesichtserkennung zur Massenüberwachung</title>
  <link rel="stylesheet" href="css/styles.css">
</head>

<body class="has-background-dark">
  <div class="container has-background-white">
    <div class="columns">
      <div class="column is-10-desktop is-offset-1-desktop">

        <nav class="navbar" role="navigation" aria-label="main navigation">
          <div class="navbar-brand">

            <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
            </a>
          </div>

          <div id="navbarBasicExample" class="navbar-menu">

              <div class="navbar-end">
                <a class="navbar-item is-tab" href="#unterstützende">
                  Unterstützende
                </a>
                <a class="navbar-item is-tab" href="#über-das-projekt">
                  Über das Projekt
                </a>
              </div>

          </div>
        </nav>     
        
      </div>
    </div>
  </div>

  <div class="container has-background-white">
    <section class="hero is-medium is-primary">
      <div class="hero-body">
        <div class="columns">
          <div class="column is-8-desktop is-offset-2-desktop">
            <h1 class="title is-2 is-spaced is-uppercase">
              Keine Gesichts&shy;erkennung<br /> zur Massen&shy;überwachung
            </h1>
          </div>
        </div>
      </div>
    </section>
